import os
from datetime import datetime

journal_file = ".Jules/palette.md"
os.makedirs(os.path.dirname(journal_file), exist_ok=True)

entry = f"""## {datetime.now().strftime('%Y-%m-%d')} - Terminal Raw Mode Keyboard Traps
**Learning:** When a terminal UI uses `tty.setraw()` to read individual keystrokes, standard interrupt signals (like `SIGINT` from Ctrl-C) are not generated by the terminal driver. Instead, the literal byte `\\x03` is passed through. If the UI does not explicitly handle `\\x03`, it creates a "keyboard trap" where users cannot exit using standard shortcuts.
**Action:** Always map standard interrupt bytes (e.g., `\\x03` for Ctrl-C, `\\x04` for Ctrl-D) to the appropriate escape/cancel actions when implementing raw-mode character reading. Update prompt hints to inform users they can use Ctrl-C or Esc to cancel.
"""

content = ""
if os.path.exists(journal_file):
    with open(journal_file, "r") as f:
        content = f.read()

if entry not in content:
    with open(journal_file, "a") as f:
        f.write(entry + "\n")
