/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

export const WITTY_LOADING_PHRASES = [
  "I'm Feeling Lucky",
  'Shipping awesomeness',
  'Painting the serifs back on',
  'Navigating the slime mold',
  'Consulting the digital spirits',
  'Reticulating splines',
  'Warming up the AI hamsters',
  'Asking the magic conch shell',
  'Generating witty retort',
  'Polishing the algorithms',
  "Don't rush perfection (or my code)",
  'Brewing fresh bytes',
  'Counting electrons',
  'Engaging cognitive processors',
  'Checking for syntax errors in the universe',
  'One moment, optimizing humor',
  'Shuffling punchlines',
  'Untangling neural nets',
  'Compiling brilliance',
  'Loading wit.exe',
  'Summoning the cloud of wisdom',
  'Preparing a witty response',
  "Just a sec, I'm debugging reality",
  'Confuzzling the options',
  'Tuning the cosmic frequencies',
  'Crafting a response worthy of your patience',
  'Compiling the 1s and 0s',
  'Resolving dependencies… and existential crises',
  'Defragmenting memories… both RAM and personal',
  'Rebooting the humor module',
  'Caching the essentials (mostly cat memes)',
  'Optimizing for ludicrous speed',
  "Swapping bits… don't tell the bytes",
  'Garbage collecting… be right back',
  'Assembling the interwebs',
  'Converting coffee into code',
  'Updating the syntax for reality',
  'Rewiring the synapses',
  'Looking for a misplaced semicolon',
  "Greasin' the cogs of the machine",
  'Pre-heating the servers',
  'Calibrating the flux capacitor',
  'Engaging the improbability drive',
  'Channeling the Force',
  'Aligning the stars for optimal response',
  'So say we all',
  'Loading the next great idea',
  "Just a moment, I'm in the zone",
  'Preparing to dazzle you with brilliance',
  "Just a tick, I'm polishing my wit",
  "Hold tight, I'm crafting a masterpiece",
  "Just a jiffy, I'm debugging the universe",
  "Just a moment, I'm aligning the pixels",
  "Just a sec, I'm optimizing the humor",
  "Just a moment, I'm tuning the algorithms",
  'Warp speed engaged',
  'Mining for more Dilithium crystals',
  "Don't panic",
  'Following the white rabbit',
  'The truth is in here… somewhere',
  'Blowing on the cartridge',
  'Loading… Do a barrel roll!',
  'Waiting for the respawn',
  'Finishing the Kessel Run in less than 12 parsecs',
  "The cake is not a lie, it's just still loading",
  'Fiddling with the character creation screen',
  "Just a moment, I'm finding the right meme",
  "Pressing 'A' to continue",
  'Herding digital cats',
  'Polishing the pixels',
  'Finding a suitable loading screen pun',
  'Distracting you with this witty phrase',
  'Almost there… probably',
  'Our hamsters are working as fast as they can',
  'Giving Cloudy a pat on the head',
  'Petting the cat',
  'Rickrolling my boss',
  'Slapping the bass',
  'Tasting the snozberries',
  "I'm going the distance, I'm going for speed",
  'Is this the real life? Is this just fantasy?',
  "I've got a good feeling about this",
  'Poking the bear',
  'Doing research on the latest memes',
  'Figuring out how to make this more witty',
  'Hmmm… let me think',
  'What do you call a fish with no eyes? A fsh',
  'Why did the computer go to therapy? It had too many bytes',
  "Why don't programmers like nature? It has too many bugs",
  'Why do programmers prefer dark mode? Because light attracts bugs',
  'Why did the developer go broke? Because they used up all their cache',
  "What can you do with a broken pencil? Nothing, it's pointless",
  'Applying percussive maintenance',
  'Searching for the correct USB orientation',
  'Ensuring the magic smoke stays inside the wires',
  'Rewriting in Rust for no particular reason',
  'Trying to exit Vim',
  'Spinning up the hamster wheel',
  "That's not a bug, it's an undocumented feature",
  'Engage.',
  "I'll be back… with an answer.",
  'My other process is a TARDIS',
  'Communing with the machine spirit',
  'Letting the thoughts marinate',
  'Just remembered where I put my keys',
  'Pondering the orb',
  "I've seen things you people wouldn't believe… like a user who reads loading messages.",
  'Initiating thoughtful gaze',
  "What's a computer's favorite snack? Microchips.",
  "Why do Java developers wear glasses? Because they don't C#.",
  'Charging the laser… pew pew!',
  'Dividing by zero… just kidding!',
  'Looking for an adult superviso… I mean, processing.',
  'Making it go beep boop.',
  'Buffering… because even AIs need a moment.',
  'Entangling quantum particles for a faster response',
  'Polishing the chrome… on the algorithms.',
  'Are you not entertained? (Working on it!)',
  'Summoning the code gremlins… to help, of course.',
  'Just waiting for the dial-up tone to finish',
  'Recalibrating the humor-o-meter.',
  'My other loading screen is even funnier.',
  "Pretty sure there's a cat walking on the keyboard somewhere",
  'Enhancing… Enhancing… Still loading.',
  "It's not a bug, it's a feature… of this loading screen.",
  'Have you tried turning it off and on again? (The loading screen, not me.)',
  'Constructing additional pylons',
  'New line? That’s Ctrl+J.',
  'Releasing the HypnoDrones',
  'Pushing the button, Frank.',
];
