"""
This file contains the `Interpreter` class which is responsible for:

- Initializing the interpreter with the necessary configurations and arguments.
- Handling different modes of operation: Code, Script, and Command.
- Generating code based on the user's input and the selected mode.
- Executing the generated code if the user chooses to do so.
- Handling errors during code execution and attempting to resolve them by installing missing packages.
- Cleaning up response files after each iteration.
- Opening resource files such as graphs, charts, and tables generated by the code.
- Logging all important actions and errors for debugging and traceability.
"""

import os
import subprocess
import time
import json
import litellm  # Main libray for LLM's
from typing import List
import requests
import re
from libs.code_interpreter import CodeInterpreter
from libs.history_manager import History
from libs.logger import Logger
from libs.markdown_code import display_code, display_markdown_message
from libs.model_utils import normalize_model_name
from libs.package_manager import PackageManager
from libs.safety_manager import ExecutionSafetyManager, RepairCircuitBreaker
from libs.terminal_ui import TerminalUI
from libs.utility_manager import UtilityManager
from dotenv import load_dotenv
import shutil
from rich.console import Console

litellm.set_verbose = False
litellm.suppress_debug_info = True
litellm.telemetry = False

class Interpreter:
	logger = None
	client = None
	interpreter_version = None
	console = Console()
	
	def __init__(self,  args):
		self.args = args
		self.history = []
		self.history_count = 3
		self.history_file = "history/history.json"
		self.utility_manager = UtilityManager()
		self.code_interpreter = CodeInterpreter()
		self.package_manager = PackageManager()
		self.history_manager = History(self.history_file)
		self.logger = Logger.initialize("logs/interpreter.log")
		self.client = None
		self.config_values = None
		self.system_message = ""
		self.gemini_vision = None
		self.safety_manager = ExecutionSafetyManager()
		self.UNSAFE_EXECUTION = getattr(self.args, "unsafe", False)
		self.MAX_REPAIR_ATTEMPTS = 3
		self.MAX_LLM_RETRIES = 3
		self.terminal_ui = TerminalUI() if getattr(self.args, "tui", False) else None
		self._last_execution_approved = False
		self.initialize()
	
	def initialize(self):
		self.INTERPRETER_LANGUAGE = self.args.lang if self.args.lang else 'python'
		self.SAVE_CODE = self.args.save_code
		self.EXECUTE_CODE = self.args.exec
		self.DISPLAY_CODE = self.args.display_code
		self.INTERPRETER_MODEL = self.args.model if self.args.model else None
		self.INTERPRETER_MODEL_LABEL = self.args.model if self.args.model else None
		self.logger.info(f"Interpreter args model selected is '{self.args.model}")
		self.logger.info(f"Interpreter model selected is '{self.INTERPRETER_MODEL}'")
		self.system_message = ""
		self.INTERPRETER_MODE = self.args.mode if self.args.mode else 'code'
		
		if self.args.file is None:
			self.INTERPRETER_PROMPT_FILE = False
			self.INTERPRETER_PROMPT_INPUT = True
		else:
			self.INTERPRETER_PROMPT_FILE = True
			self.INTERPRETER_PROMPT_INPUT = False
			# If the user didn't provide a file name, use the default one
			if self.args.file == '':
				self.args.file = 'prompt.txt'
				
		# Set the history optional(Argparse)
		if hasattr(self.args, 'history'):
			self.INTERPRETER_HISTORY = self.args.history
		else:
			self.INTERPRETER_HISTORY = False

		if self.INTERPRETER_MODE == 'vision':
			self.system_message = "You are top tier image captioner and image analyzer. Please generate a well-written description of the image that is precise, easy to understand"
		elif self.INTERPRETER_MODE == 'chat':
			self.system_message = "You are top tier chatbot. Please generate a well-written response that is precise, easy to understand"
		else:
			# Open file system_message.txt to a variable system_message
			try:
				with open('system/system_message.txt', 'r') as file:
					self.system_message = file.read()
					if self.system_message != "":
						self.logger.info("System message read successfully")
			except Exception as exception:
				self.logger.error(f"Error occurred while reading system_message.txt: {str(exception)}")
				raise
		
		# Initialize client and mode.
		self.initialize_client()
		self.initialize_mode()
		
		try: # Make this as optional step to have readline history.
			self.utility_manager.initialize_readline_history()
		except Exception:
			self.logger.error("Exception on initializing readline history")

	def _is_recoverable_runtime_error(self, error_text):
		recoverable_errors = [
			"rate limit",
			"ratelimit",
			"quota",
			"credits",
			"requires more credits",
			"resource_exhausted",
			"temporarily rate-limited",
			"402",
			"429",
			"api key",
			"authentication",
			"unauthorized",
			"model_not_found",
			"not found",
			"timeout",
			"connection",
		]
		error_text = (error_text or "").lower()
		return any(error in error_text for error in recoverable_errors)

	def _format_runtime_error_message(self, error_text):
		message = error_text or "Unknown error"
		message = re.sub(r"https?://\S+", "", message)
		message = re.sub(r"litellm\.[A-Za-z]+Error:\s*", "", message)
		message = re.sub(r"\b[A-Za-z]+Error:\s*", "", message)
		message = re.sub(r"\b[A-Za-z]+Exception\s*-\s*", "", message)
		message = re.sub(r"For more information on this error.*", "", message, flags=re.IGNORECASE)
		message = re.sub(r"\s+", " ", message).strip(" .")
		return message

	def _is_retryable_request_error(self, error_text):
		error_text = (error_text or "").lower()
		retryable_markers = [
			"rate limit",
			"ratelimit",
			"timeout",
			"temporarily unavailable",
			"temporarily rate-limited",
			"connection",
			"503",
			"502",
			"429",
			"overloaded",
			"provider returned error",
			"try again",
		]
		non_retryable_markers = [
			"quota",
			"credits",
			"requires more credits",
			"billing",
			"api key",
			"authentication",
			"unauthorized",
			"model_not_found",
		]
		if any(marker in error_text for marker in non_retryable_markers):
			return False
		return any(marker in error_text for marker in retryable_markers)

	def _generate_content_with_retries(self, message, chat_history, config_values=None, image_file=None):
		last_exception = None
		for attempt in range(1, self.MAX_LLM_RETRIES + 1):
			try:
				return self.generate_content(message, chat_history, config_values=config_values, image_file=image_file)
			except Exception as exception:
				last_exception = exception
				error_text = str(exception)
				if attempt >= self.MAX_LLM_RETRIES or not self._is_retryable_request_error(error_text):
					raise
				display_markdown_message(f"LLM request retry {attempt}/{self.MAX_LLM_RETRIES} after transient failure.")
				time.sleep(min(attempt, 3))
		if last_exception:
			raise last_exception

	def _apply_mode(self, mode):
		modes = {'vision': 'VISION_MODE', 'script': 'SCRIPT_MODE', 'command': 'COMMAND_MODE', 'code': 'CODE_MODE', 'chat': 'CHAT_MODE'}
		self.INTERPRETER_MODE = mode.lower()
		for key in modes:
			setattr(self, modes[key], self.INTERPRETER_MODE == key)

	def _open_tui_settings(self, setting_type):
		if not self.terminal_ui:
			return None
		if setting_type == "mode":
			return {"mode": self.terminal_ui.select_mode(self.INTERPRETER_MODE)}
		if setting_type == "model":
			return {"model": self.terminal_ui.select_model(self.INTERPRETER_MODEL_LABEL or self.INTERPRETER_MODEL)}
		if setting_type == "language":
			return {"language": self.terminal_ui.select_language(self.INTERPRETER_LANGUAGE)}
		if setting_type == "settings":
			return self.terminal_ui.interactive_settings(self)
		return None

	def _apply_runtime_settings(self, settings):
		if not settings:
			return
		if "mode" in settings and settings["mode"]:
			self._apply_mode(settings["mode"])
		if "language" in settings and settings["language"]:
			self.INTERPRETER_LANGUAGE = settings["language"]
		if "display_code" in settings:
			self.DISPLAY_CODE = settings["display_code"]
		if "execute_code" in settings:
			self.EXECUTE_CODE = settings["execute_code"]
		if "save_code" in settings:
			self.SAVE_CODE = settings["save_code"]
		if "history" in settings:
			self.INTERPRETER_HISTORY = settings["history"]
		if "model" in settings and settings["model"]:
			model = settings["model"]
			model_config_file = f"configs/{model}.json"
			if not os.path.isfile(model_config_file):
				display_markdown_message(f"Model {model} does not exists. Please check the model name using '/list' command.")
			else:
				self.INTERPRETER_MODEL = model
				self.INTERPRETER_MODEL_LABEL = model
				self.initialize_client()

	def _display_session_banner(self, os_name, input_prompt_mode):
		short_lang = "python" if self.INTERPRETER_LANGUAGE == "python" else "javascript"
		short_prompt_mode = "input" if input_prompt_mode.lower() == "input" else "file"
		short_os_name = os_name.replace("Windows ", "Win")
		session_line = (
			f"OS={short_os_name} | Lang={short_lang} | "
			f"Mode={self.INTERPRETER_MODE} | Src={short_prompt_mode} | "
			f"Model={self.INTERPRETER_MODEL_LABEL or self.INTERPRETER_MODEL}"
		)
		self.console.print(f"[bold bright_blue]{session_line}[/bold bright_blue]", overflow="ignore", no_wrap=True)

	def _build_repair_prompt(self, task, prompt, code_snippet, error_text, os_name, code_output=None):
		if self.COMMAND_MODE:
			target = "single terminal command"
		elif self.SCRIPT_MODE:
			target = "script"
		else:
			target = f"{self.INTERPRETER_LANGUAGE} code"

		observed_output = ""
		if code_output:
			observed_output = f"\nObserved stdout before failure:\n{code_output}\n"

		return (
			f"You are in bounded repair mode for a failed {target} execution.\n"
			f"Original task: {task}\n"
			f"Resolved prompt: {prompt}\n"
			f"Operating system: {os_name}\n"
			f"Generated content:\n{code_snippet}\n\n"
			f"{observed_output}"
			f"Execution error:\n{error_text}\n\n"
			f"Think through the failure privately, then return only the corrected {target} inside one triple-backtick block.\n"
			"Preserve only the parts that help complete the original task, and remove unrelated extras.\n"
			"Do not include explanations, comments, or any text outside the code block."
		)

	def _task_has_any(self, text, phrases):
		return any(phrase in text for phrase in phrases)

	def _is_simple_directory_listing_task(self, task_lower):
		if not task_lower:
			return False

		list_phrases = (
			"print current files",
			"list current files",
			"show current files",
			"print files in directory",
			"list files in directory",
			"show files in directory",
			"print files in the directory",
			"list files in the directory",
			"show files in the directory",
			"print files in current directory",
			"list files in current directory",
			"show files in current directory",
			"print current files in directory",
			"list current files in directory",
			"show current files in directory",
		)
		disallowed = ("chart", "graph", "plot", "table", "markdown", "html", "png", "csv", "image", "size in mb", "size")
		return self._task_has_any(task_lower, list_phrases) and not self._task_has_any(task_lower, disallowed)

	def _maybe_simplify_generated_code(self, task, code_snippet):
		if not self.CODE_MODE or not isinstance(task, str) or not isinstance(code_snippet, str):
			return code_snippet

		task_lower = task.lower()
		exact_print_match = re.search(r"print(?:s)? exactly ['\"](.+?)['\"]", task, re.IGNORECASE)
		if exact_print_match:
			literal = exact_print_match.group(1)
			if self.INTERPRETER_LANGUAGE == "python":
				return f"print({literal!r})"
			if self.INTERPRETER_LANGUAGE == "javascript":
				return f"console.log({literal!r})"

		if "current working directory" in task_lower and self.CODE_MODE:
			if self.INTERPRETER_LANGUAGE == "python":
				return "import os\nprint(os.getcwd())"
			if self.INTERPRETER_LANGUAGE == "javascript":
				return "console.log(process.cwd())"

		if self._is_simple_directory_listing_task(task_lower):
			if self.INTERPRETER_LANGUAGE == "python":
				return "import os\nfor name in os.listdir():\n    print(name)"
			if self.INTERPRETER_LANGUAGE == "javascript":
				return "const fs = require('fs');\nfor (const name of fs.readdirSync(process.cwd())) {\n  console.log(name);\n}"

		return code_snippet

	def _execute_generated_output(self, code_snippet, os_name, force_execute=False):
		decision = self.safety_manager.assess_execution(code_snippet, self.INTERPRETER_MODE)
		if not self.UNSAFE_EXECUTION and not decision.allowed:
			reason_text = "; ".join(decision.reasons)
			display_markdown_message(f"Execution blocked by safety policy: {reason_text}")
			display_markdown_message("Use `--unsafe` only if you explicitly trust the generated output.")
			return None, f"Safety blocked: {reason_text}"

		if not self.UNSAFE_EXECUTION:
			sandbox_context = self.safety_manager.build_sandbox_context()
		else:
			sandbox_context = None
		try:
			return self.execute_code(code_snippet, os_name, sandbox_context=sandbox_context, force_execute=force_execute)
		finally:
			if not self.UNSAFE_EXECUTION:
				self.safety_manager.cleanup_sandbox_context(sandbox_context)

	def _attempt_repair_after_failure(self, task, prompt, code_snippet, code_error, os_name, start_sep, end_sep, extracted_file_name, code_output=None):
			circuit_breaker = RepairCircuitBreaker(max_attempts=self.MAX_REPAIR_ATTEMPTS)
			current_snippet = code_snippet
			current_error = code_error
			current_output = code_output

			while current_error and circuit_breaker.should_continue(current_error):
				display_markdown_message(f"Repair attempt {circuit_breaker.attempts}/{circuit_breaker.max_attempts} after execution failure.")
				repair_prompt = self._build_repair_prompt(task, prompt, current_snippet, current_error, os_name, code_output=current_output)
				repaired_output = self._generate_content_with_retries(repair_prompt, self.history, config_values=self.config_values, image_file=extracted_file_name)
				repaired_snippet = self.code_interpreter.extract_code(repaired_output, start_sep, end_sep)
				repaired_snippet = self._maybe_simplify_generated_code(task, repaired_snippet)

				if not repaired_snippet:
					current_error = "Failed to extract repaired output from model response."
					continue

				if repaired_snippet.strip() == current_snippet.strip():
					current_output, current_error = self._execute_generated_output(repaired_snippet, os_name, force_execute=False)
					if current_output:
						return repaired_snippet, current_output, current_error
					if not current_error:
						return repaired_snippet, current_output, None
					if current_error.startswith("Safety blocked:"):
						return repaired_snippet, current_output, current_error
					break

				current_snippet = repaired_snippet
				display_language = self.INTERPRETER_LANGUAGE if self.CODE_MODE else 'bash'
				display_code(current_snippet, language=display_language)
				current_output, current_error = self._execute_generated_output(current_snippet, os_name, force_execute=False)

				if current_output:
					return current_snippet, current_output, current_error
				if not current_error:
					return current_snippet, current_output, None
				if current_error.startswith("Safety blocked:"):
					return current_snippet, current_output, current_error

			return current_snippet, current_output, current_error

	def _safe_input(self, prompt_text, default=None):
		try:
			return input(prompt_text)
		except EOFError:
			return default

	def initialize_client(self):
		env_path = os.path.join(os.getcwd(), ".env")
		load_dotenv(dotenv_path=env_path, override=True)
		self.logger.info("Initializing Client")
		config_file_name: str = ""

		self.logger.info(f"Interpreter model selected is '{self.INTERPRETER_MODEL}'")
		if self.INTERPRETER_MODEL is None or self.INTERPRETER_MODEL == "":
			self.logger.info("Model is not provided, using default model.")
			self.INTERPRETER_MODEL = self.utility_manager.get_default_model_name()
			self.INTERPRETER_MODEL_LABEL = self.INTERPRETER_MODEL
			config_file_name = f"configs/{self.INTERPRETER_MODEL}.json"
		else:
			self.INTERPRETER_MODEL_LABEL = self.INTERPRETER_MODEL
			config_file_name = f"configs/{self.INTERPRETER_MODEL}.json"
		
		self.logger.info(f"Reading config file {config_file_name}")    
		self.config_values = self.utility_manager.read_config_file(config_file_name)
		self.INTERPRETER_MODEL = str(self.config_values.get('model', self.INTERPRETER_MODEL))       
		model_name = self.INTERPRETER_MODEL.strip().split("/")[-1]
		
		# skip init client for local models.(Bug#10 https://github.com/haseeb-heaven/code-interpreter/issues/10)
		if 'local' in self.INTERPRETER_MODEL:
			self.logger.info("Skipping client initialization for local model.")
			# Add OpenAI API key if not present in the environment variables. (https://github.com/haseeb-heaven/code-interpreter/issues/13)
			# Fixed OpenAI API Key name (https://github.com/haseeb-heaven/code-interpreter/issues/20)
			api_key = os.getenv('OPENAI_API_KEY')
			
			if api_key:
				self.logger.info("Using local API key from environment variables.")
				
			if api_key is None:
				load_dotenv(dotenv_path=env_path, override=True)
				api_key = os.getenv('OPENAI_API_KEY')
				if api_key is None:
					self.logger.info("Setting default local API key for local models.")
					os.environ['OPENAI_API_KEY'] = "sk-1234567890" # Setting default API key for local models.
			return
		
		self.logger.info(f"Using model {model_name}")

		config_provider = str(self.config_values.get("provider", "")).strip().lower()

		if config_provider == "nvidia" or self.INTERPRETER_MODEL.startswith("nvidia/"):
			api_key_info = {"key_name": "NVIDIA_API_KEY", "prefix": "nvapi-"}
		elif config_provider in ("z-ai", "zai") or self.INTERPRETER_MODEL.startswith(("glm-", "z-ai/", "zai/")):
			api_key_info = {"key_name": "Z_AI_API_KEY", "prefix": None, "length": 10}
		elif config_provider in ("browser-use", "browser_use") or self.INTERPRETER_MODEL.startswith(("bu-", "browser-use/")):
			api_key_info = {"key_name": "BROWSER_USE_API_KEY", "prefix": "bu_"}
		elif config_provider == "openrouter":
			api_key_info = {"key_name": "OPENROUTER_API_KEY", "prefix": "sk-or-v1-"}
		elif self.INTERPRETER_MODEL.startswith(("gpt", "o1", "o3", "o4")):
			api_key_info = {"key_name": "OPENAI_API_KEY", "prefix": "sk-"}
		elif self.INTERPRETER_MODEL.startswith("groq/") or "groq" in self.INTERPRETER_MODEL:
			api_key_info = {"key_name": "GROQ_API_KEY", "prefix": "gsk"}
		elif "claude" in self.INTERPRETER_MODEL:
			api_key_info = {"key_name": "ANTHROPIC_API_KEY", "prefix": "sk-ant-"}
		elif "gemini" in self.INTERPRETER_MODEL:
			api_key_info = {"key_name": "GEMINI_API_KEY", "prefix": None, "length": 15}
		elif "deepseek" in self.INTERPRETER_MODEL:
			api_key_info = {"key_name": "DEEPSEEK_API_KEY", "prefix": None, "length": 10}
		else:
			api_key_info = {"key_name": "HUGGINGFACE_API_KEY", "prefix": "hf_"}

		api_key_name = api_key_info["key_name"]
		api_key = os.getenv(api_key_name)
		if api_key is None:
			load_dotenv(dotenv_path=env_path, override=True)
			api_key = os.getenv(api_key_name)
		if not api_key:
			raise Exception(f"{api_key_name} not found in .env file.")
		if api_key_info.get("prefix") and not api_key.startswith(api_key_info["prefix"]):
			raise Exception(f"{api_key_name} should start with '{api_key_info['prefix']}'. Please check your .env file.")
		if api_key_info.get("length") and len(api_key) <= api_key_info["length"]:
			raise Exception(f"{api_key_name} should have length greater than {api_key_info['length']}. Please check your .env file.")
		
	def initialize_mode(self):
		self.CODE_MODE = True if self.args.mode == 'code' else False
		self.SCRIPT_MODE = True if self.args.mode == 'script' else False
		self.COMMAND_MODE = True if self.args.mode == 'command' else False
		self.VISION_MODE = True if self.args.mode == 'vision' else False
		self.CHAT_MODE = True if self.args.mode == 'chat' else False
		if not self.SCRIPT_MODE and not self.COMMAND_MODE and not self.VISION_MODE and not self.CHAT_MODE:
			self.CODE_MODE = True
	
	def get_prompt(self, message: str, chat_history: List[dict]) -> List[dict] | str:
		system_message: str = ""
		assistant_message = "Please generate code wrapped inside triple backticks known as codeblock."
		
		if self.CODE_MODE:
			system_message = (
				self.system_message
				+ "\nReturn exactly one executable code block."
				+ "\nDo not include explanations, comments, docstrings, markdown headings, or text outside the code block."
				+ "\nDo not use subprocess, os.system, or any shell execution."
				+ "\nOnly create tables, charts, plots, files, or visual outputs IF explicitly required."
				+ "\nIf not explicitly requested, do NOT generate them."
			)
			assistant_message = (
				f"Return only executable {self.INTERPRETER_LANGUAGE} code wrapped in triple backticks."
				f" No explanations. No comments. No text outside the code block."
				f" Do not use subprocess, os.system, or shell execution."
			)

		elif self.SCRIPT_MODE:
			system_message = (
				"Generate a Python script only."
				"\nSTRICT RULES:"
				"\n- Do NOT use bash, sh, cmd, or powershell"
				"\n- Do NOT use subprocess, os.system, or shell execution"
				"\n- Script must be fully self-contained and executable"
				"\n- Return exactly one code block with no explanations"
			)
			assistant_message = (
				"Return only Python script inside triple backticks."
				" No explanations. No comments outside code."
			)

		elif self.COMMAND_MODE:
			system_message = (
				"Generate only a single executable command."
				"\nSTRICT RULES:"
				"\n- Do NOT use shell built-in commands (dir, ls, cd, copy, del, Get-ChildItem)"
				"\n- Do NOT use cmd, powershell, bash, or shell syntax"
				"\n- Do NOT use &&, ||, |, ;, >, <, $, or chaining"
				"\n- Always use python -c for filesystem or logic tasks"
				"\n- Command must be directly executable without shell"
			)
			assistant_message = (
				"Return only a single-line executable command."
				" Do NOT return a code block."
				" Do NOT use triple backticks."
				" No explanations. No extra text."
			)

		elif self.VISION_MODE:
			system_message = (
				"Please generate a well-written description of the image that is precise, easy to understand"
			)
			assistant_message = (
				"Return only the description. No code. No formatting. No markdown."
			)

		elif self.CHAT_MODE:
			system_message = "Please generate a well-written response that is precise, easy to understand"
			assistant_message = "Return a clear and helpful response."
			
			if chat_history:
				system_message += (
					"\n\nThis is user chat history. Use it as context if needed:\n\n"
					+ str(chat_history)
				)

		# If using Claude (Anthropic), format message as structured content list (no system/assistant roles supported)
		if 'claude' in self.INTERPRETER_MODEL:
			combined = f"{system_message}\n\n{assistant_message}\n\nUser: {message}"
			messages = [
				{
					"role": "user",
					"content": [
						{
							"type": "text",
							"text": combined
						}
					]
				}
			]

		# Otherwise, use standard chat format with system + assistant + user messages (OpenAI-style)
		else:
			messages = [
				{"role": "system", "content": system_message},
				{"role": "assistant", "content": assistant_message},
				{"role": "user", "content": message}
			]
		
		return messages

	def execute_last_code(self, os_name):
		try:
			code_file, code_snippet = self.utility_manager.get_output_history(mode=self.INTERPRETER_MODE, os_name=os_name, language=self.INTERPRETER_LANGUAGE)

			# check if the code is empty
			if code_snippet is None or code_file is None:
				self.logger.error("Code history or file is empty.")
				display_markdown_message("Code history or file is empty. - Please use **-s** flag or **/save** command to save the code.")
				return
			
			display_code(code_snippet)  # Display the code first.

			# Execute the code if the user has selected.
			code_output, code_error = self._execute_generated_output(code_snippet, os_name)
			if code_output:
				self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed successfully.")
				display_code(code_output)
				self.logger.info(f"Output: {code_output[:100]}")
			elif code_error:
				self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed with error.")
				display_markdown_message(f"Error: {code_error}")
		except Exception as exception:
			self.logger.error(f"Error in processing command run code: {str(exception)}")
			raise

	def _extract_latest_user_text(self, message, messages):
		if isinstance(message, str) and message.strip():
			return message.strip()
		if isinstance(messages, list):
			for item in reversed(messages):
				if not isinstance(item, dict) or item.get("role") != "user":
					continue
				content = item.get("content")
				if isinstance(content, str) and content.strip():
					return content.strip()
				if isinstance(content, list):
					text_parts = []
					for chunk in content:
						if isinstance(chunk, dict) and chunk.get("type") == "text":
							text_parts.append(str(chunk.get("text", "")).strip())
					joined = " ".join(part for part in text_parts if part)
					if joined:
						return joined
		return "Help with this request."

	def _run_openai_compatible_completion(self, api_key_name, messages, temperature, max_tokens, api_base, extra_headers=None):
		api_key = os.getenv(api_key_name)
		if not api_key:
			raise Exception(f"{api_key_name} not found in .env file.")
		if api_base == 'None':
			raise Exception("Exception api base not set for custom model")
		custom_llm_provider = "openai"
		completion_kwargs = {
			"messages": messages,
			"temperature": temperature,
			"max_tokens": max_tokens,
			"api_base": api_base,
			"api_key": api_key,
			"custom_llm_provider": custom_llm_provider,
		}
		if extra_headers:
			completion_kwargs["extra_headers"] = extra_headers
		return litellm.completion(self.INTERPRETER_MODEL, **completion_kwargs)

	def _generate_browser_use_content(self, message, messages, config_values):
		api_key = os.getenv("BROWSER_USE_API_KEY")
		if not api_key:
			raise Exception("BROWSER_USE_API_KEY not found in .env file.")

		base_url = str(config_values.get("api_base", "https://api.browser-use.com/api/v3")).rstrip("/")
		model = self.INTERPRETER_MODEL
		task = self._extract_latest_user_text(message, messages)
		timeout_seconds = int(config_values.get("browser_use_timeout", 150))
		poll_interval = int(config_values.get("browser_use_poll_interval", 3))

		headers = {
			"X-Browser-Use-API-Key": api_key,
			"Content-Type": "application/json",
		}
		payload = {
			"task": task,
			"model": model,
			"keepAlive": False,
		}
		self.logger.info(f"Starting Browser Use session with model={model}")
		create_response = requests.post(f"{base_url}/sessions", headers=headers, json=payload, timeout=45)
		create_response.raise_for_status()
		create_data = create_response.json()
		session_id = create_data.get("id")
		if not session_id:
			raise Exception("Browser Use session creation failed: missing session id")

		end_time = time.time() + timeout_seconds
		while time.time() < end_time:
			status_response = requests.get(f"{base_url}/sessions/{session_id}", headers=headers, timeout=30)
			status_response.raise_for_status()
			status_data = status_response.json()
			status = str(status_data.get("status", "")).lower()
			live_url = status_data.get("liveUrl")

			if status in {"finished", "completed", "stopped", "done", "success"}:
				output = status_data.get("output")
				if output is None:
					output = status_data.get("result")
				if output is None:
					output = status_data.get("finalResult")
				if output is None and live_url:
					output = f"Browser Use session completed. Live URL: {live_url}"
				if output is None:
					output = f"Browser Use session completed. Session ID: {session_id}"
				if isinstance(output, (dict, list)):
					return json.dumps(output, ensure_ascii=False)
				return str(output)

			if status in {"failed", "error", "cancelled"}:
				raise Exception(f"Browser Use session failed with status '{status}'")

			time.sleep(poll_interval)

		raise Exception("Browser Use session timed out.")
	
	def generate_content(self, message, chat_history: list[tuple[str, str]], temperature=0.1, max_tokens=1024,config_values=None,image_file=None):
		from libs.llm_dispatcher import build_completion_kwargs

		self.logger.info(f"Generating content with args: message={message}, chat_history={chat_history}, temperature={temperature}, max_tokens={max_tokens}, config_values={config_values}, image_file={image_file}")
		self.logger.info(f"Interpreter model selected is '{self.INTERPRETER_MODEL}'")
		api_base = 'None'
		config_provider = ""
		
		# Use the values from the config file if they are provided
		if config_values:
			temperature = float(config_values.get('temperature', temperature))
			max_tokens = int(config_values.get('max_tokens', max_tokens))
			api_base = str(config_values.get('api_base', None)) # Only for OpenAI.
			config_provider = str(config_values.get("provider", "")).strip().lower()

		# Get the system prompt
		messages = self.get_prompt(message, chat_history)

		# ── Special case: Browser-Use (does not use litellm) ────────────
		if config_provider in ("browser-use", "browser_use") or self.INTERPRETER_MODEL.startswith(("bu-", "browser-use/")):
			self.logger.info("Model is Browser Use session model.")
			response_text = self._generate_browser_use_content(message, messages, config_values or {})
			self.logger.info("Response received from Browser Use session.")
			return response_text

		# ── Special case: Gemini Vision (does not use litellm) ──────────
		if 'gemini' in self.INTERPRETER_MODEL and self.INTERPRETER_MODE == 'vision':
			try:
				from libs.gemini_vision import GeminiVision
				self.gemini_vision = GeminiVision()
			except Exception as exception:
				self.logger.error(f"Error importing Gemini Vision: {exception}")
				raise

			self.logger.info("Model is Gemini Pro Vision.")
			if not image_file:
				self.logger.error("Image file is not valid or Corrupted.")
				raise ValueError("Image file is not valid or Corrupted.")

			if 'http' in image_file or 'https' in image_file or 'www.' in image_file:
				self.logger.info("Image contains URL.")
				response = self.gemini_vision.gemini_vision_url(prompt=messages, image_url=image_file)
			else:
				self.logger.info("Image contains file.")
				response = self.gemini_vision.gemini_vision_path(prompt=messages, image_path=image_file)

			self.logger.info("Response received from completion function.")
			return response  # Gemini Vision is not a coding model.

		# ── Normalize model name for providers that need it ─────────────
		self.INTERPRETER_MODEL = normalize_model_name(self.INTERPRETER_MODEL)

		# ── Build kwargs and make a single litellm.completion call ──────
		kwargs = build_completion_kwargs(
			model=self.INTERPRETER_MODEL,
			messages=messages,
			temperature=temperature,
			max_tokens=max_tokens,
			config_provider=config_provider,
			api_base=api_base,
		)
		self.logger.info(f"Calling litellm.completion for provider-resolved kwargs (keys: {list(kwargs.keys())})")
		response = litellm.completion(self.INTERPRETER_MODEL, **kwargs)
		self.logger.info("Response received from completion function.")

		self.logger.info(f"Generated text {response}")
		generated_text = self.utility_manager._extract_content(response)
		self.logger.info(f"Generated content {generated_text}")
		return generated_text
	
	def get_code_prompt(self,  task, os_name):
		
		if self.INTERPRETER_LANGUAGE not in ['python', 'javascript']:
			self.INTERPRETER_LANGUAGE = 'python'
		
		prompt = (
			f"Generate executable {self.INTERPRETER_LANGUAGE} code for this task: '{task}'.\n"
			f"Target operating system: {os_name}.\n"
			"Return exactly one fenced code block and nothing else.\n"
			"Do not include explanations, comments, docstrings, markdown prose, or usage notes.\n"
			"Use production-ready syntax with correct indentation and imports.\n"
			"Do not use subprocess, os.system, or any shell execution.\n"
			"Only create tables, charts, plots, files, or visual outputs IF the task explicitly requires them.\n"
			"If the task does NOT explicitly request tables, charts, plots, or files, do NOT generate them.\n"
			"If the task only asks to print, list, or show something, generate only the few lines needed to do that exact action.\n"
			"Handle common filesystem and permission errors safely when relevant.\n"
			"If multiple solutions exist, choose the most direct working solution."
		)
		return prompt

	def get_script_prompt(self,  task, os_name):

		# Force Python for safety and consistency
		self.INTERPRETER_LANGUAGE = 'python'
		script_type = 'Python script'

		prompt = (
			f"Generate only the {script_type} for this task:\n"
			f"Task: '{task}'\n"
			f"Operating System: {os_name}\n"
			"NOTE: Script must be fully self-contained and executable without any shell usage.\n"
			"Do NOT use bash, sh, cmd, or powershell.\n"
			"Do NOT use subprocess, os.system, or shell invocation.\n"
			"Only generate tables, charts, plots, or files IF explicitly required by the task.\n"
			"Do not generate unnecessary outputs or extra files.\n"
			"Output should only contain the script, with no additional text.\n"
			"Do not add unrelated package installs or extra logic unless required."
		)

		self.logger.info(f"Script Prompt: {prompt}")
		return prompt

	def get_command_prompt(self,  task, os_name):
		prompt = (
			f"Generate only the single executable command for this task:\n"
			f"Task: '{task}'\n"
			f"Operating System: {os_name}\n"
			"IMPORTANT: Do NOT use shell built-in commands (dir, cd, copy, del, Get-ChildItem).\n"
			"Instead, generate a python -c command to perform the task.\n"
			"The command must be directly executable without shell.\n"
			"Do not use &&, ||, |, ;, >, <, $, or chaining.\n"
			"Output only the command, nothing else."
		)
		self.logger.info(f"Command Prompt: {prompt}")
		return prompt

	def handle_vision_mode(self,  task):
		prompt = f"Give accurate and detailed information about the image provided and be very detailed about the image '{task}'."
		return prompt

	def handle_chat_mode(self,  task):
		prompt = f"Give accurate and detailed response to the question provided and be very detailed about the question '{task}'."
		return prompt

	def get_mode_prompt(self,  task, os_name):
		if self.CODE_MODE:
			self.logger.info("Getting code prompt.")
			return self.get_code_prompt(task, os_name)
		elif self.SCRIPT_MODE:
			self.logger.info("Getting script prompt.")
			return self.get_script_prompt(task, os_name)
		elif self.COMMAND_MODE:
			self.logger.info("Getting command prompt.")
			return self.get_command_prompt(task, os_name)
		elif self.VISION_MODE:
			self.logger.info("Getting vision prompt.")
			return self.handle_vision_mode(task)
		elif self.CHAT_MODE:
			self.logger.info("Getting chat prompt.")
			return self.handle_chat_mode(task)

	def execute_code(self,  extracted_code, os_name, sandbox_context=None, force_execute=False):
		# If the interpreter mode is Vision, do not execute the code.
		if self.INTERPRETER_MODE in ['vision', 'chat']:
			return None, None
		
		if force_execute or self.EXECUTE_CODE:
			execute = 'y'
		else:
			try:
				execute = input("Execute the code? (Y/N): ")
			except EOFError:
				execute = 'n'
		self._last_execution_approved = execute.lower() == 'y'
		if execute.lower() == 'y':
			try:
				code_output, code_error = "", ""
				if self.SCRIPT_MODE:
					code_output, code_error = self.code_interpreter.execute_script(script=extracted_code, os_type=os_name, sandbox_context=sandbox_context)
				elif self.COMMAND_MODE:
					code_output, code_error = self.code_interpreter.execute_command(command=extracted_code, sandbox_context=sandbox_context)
				elif self.CODE_MODE:
					code_output, code_error = self.code_interpreter.execute_code(code=extracted_code, language=self.INTERPRETER_LANGUAGE, sandbox_context=sandbox_context)
				return code_output, code_error
			except Exception as exception:
				self.logger.error(f"Error occurred while executing code: {str(exception)}")
				return None, str(exception)  # Return error message as second element of tuple
		else:
			return None, None  # Return None, None if user chooses not to execute the code

	def interpreter_main(self,  version):
		
		self.interpreter_version = version
		self.logger.info(f"Interpreter - v{self.interpreter_version}")
		
		os_platform = self.utility_manager.get_os_platform()
		os_name = os_platform[0]
		generated_output = None
		code_snippet = None
		code_output, code_error = None, None
		extracted_file_name = None 

		# Seting the mode.
		if self.SCRIPT_MODE:
			self.INTERPRETER_MODE = 'script'
		elif self.COMMAND_MODE:
			self.INTERPRETER_MODE = 'command'
		elif self.VISION_MODE:
			self.INTERPRETER_MODE = 'vision'
		elif self.CHAT_MODE:
			self.INTERPRETER_MODE = 'chat'

		start_sep = str(self.config_values.get('start_sep', '```'))
		end_sep = str(self.config_values.get('end_sep', '```'))
		
		self.logger.info(f"Mode: {self.INTERPRETER_MODE} Start separator: {start_sep}, End separator: {end_sep}")

		# Display system and Assistant information.
		input_prompt_mode = "File" if self.INTERPRETER_PROMPT_FILE else "Input"
		self._display_session_banner(os_name, input_prompt_mode)
		
		# Display the welcome message.
		display_markdown_message("Welcome to **Interpreter**, I'm here to **assist** you with your everyday tasks. ")
		
		# Main System and Assistant loop.
		running = True
		while running:
			try:
				task = None
				
				if self.INTERPRETER_PROMPT_INPUT:
					self.logger.info("Reading prompt from input.")
					# Main input prompt - System and Assistant.
					task = self._safe_input("> ", default="/exit")
				elif self.INTERPRETER_PROMPT_FILE:
					prompt_file_name = self.args.file
					
					# Setting the prompt file path.
					if not prompt_file_name:
						prompt_file_name = 'prompt.txt'
					
					prompt_file_path = os.path.join(os.getcwd(), 'system', prompt_file_name)
					
					# check if the file exists.
					if not os.path.exists(prompt_file_path):
						self.logger.error(f"Prompt file not found: {prompt_file_path}")
						user_confirmation = self._safe_input("Create a new prompt file (Y/N)?: ", default="n")
						if user_confirmation.lower() == 'y':
							self.logger.info("Creating new prompt file.")
							self.utility_manager.create_file(prompt_file_path)
							display_markdown_message("New prompt file created **successfully** ")
						else:
							self.logger.info("User declined to create new prompt file.")
							display_markdown_message("User declined to create new prompt file.\nSwitching to input mode.")
							# Switch to input mode.
							self.INTERPRETER_PROMPT_INPUT = True
							self.INTERPRETER_PROMPT_FILE = False
							
							continue
						continue
					
					display_markdown_message(f"\nEnter your task in the file **'{prompt_file_path}'**")
					
					# File mode command section.
					prompt_confirmation = self._safe_input("Execute the prompt (Y/N/P/C) (P = Prompt Mode,C = Command Mode)?: ", default="n")
					if prompt_confirmation.lower() == 'y':
						self.logger.info("Executing prompt from file.")
 
						self.logger.info(f"Executing prompt from file {prompt_file_path}")
						task = self.utility_manager.read_file(prompt_file_path)
					elif prompt_confirmation.lower() == 'n':
						self.logger.info("Waiting for user confirmation to execute prompt from file.")
						print("Waiting for user confirmation to execute prompt from file.")
						self.utility_manager.clear_screen()
						continue
					elif prompt_confirmation.lower() == 'p':
						self.INTERPRETER_PROMPT_INPUT = True
						self.INTERPRETER_PROMPT_FILE = False
						self.logger.info("Changing input mode to prompt from file.")
						self.utility_manager.clear_screen()
						continue
					elif prompt_confirmation.lower() == 'c':
						self.logger.info("Changing input mode to command from file.")
						task = self._safe_input("> ", default="/exit")
					else:
						# Invalid input mode (0x000022)
						self.logger.error("Invalid input mode.")
						self.utility_manager.clear_screen()
						continue
				
				# EXIT - Command section.
				if task.lower() == '/exit':
					break
				
				# HELP - Command section.
				elif task.lower() == '/help':
					self.utility_manager.display_help()
					continue
				
				# CLEAR - Command section.
				elif task.lower() == '/clear':
					self.utility_manager.clear_screen()
					continue

				# VERSION - Command section.
				elif task.lower() == '/version':
					self.utility_manager.display_version(self.interpreter_version)
					continue
				
				# PROMPT - Command section.
				elif task.lower() == '/prompt':
					if self.INTERPRETER_PROMPT_INPUT:
						self.INTERPRETER_PROMPT_INPUT = False
						self.INTERPRETER_PROMPT_FILE = True
						self.logger.info("Input mode changed to File.")
					else:
						self.INTERPRETER_PROMPT_INPUT = True
						self.INTERPRETER_PROMPT_FILE = False
						self.logger.info("Input mode changed to Prompt.")
					continue
				
				# HISTORY - Command section.
				elif task.lower() == '/history':
					self.INTERPRETER_HISTORY = not self.INTERPRETER_HISTORY
					display_markdown_message(f"History is {'enabled' if self.INTERPRETER_HISTORY else 'disabled'}")
					continue
				
				# SHELL - Command removed for security reasons.
				elif task.lower().startswith('/shell'):
					# The /shell feature has been intentionally removed. Inform the user.
					display_markdown_message("The '/shell' command has been removed for security reasons.")
					continue

				# LOG - Command section.
				elif task.lower() == '/debug':
					# Toggle the log level to Debug/Silent.
					logger_mode = Logger.get_current_level()

					if logger_mode.lower() == 'debug':
						Logger.set_level_to_error()
						display_markdown_message("**Debug** mode **disabled**")
					else:
						Logger.set_level_to_debug()
						display_markdown_message("**Debug** mode **enabled**")
					continue

				# LIST - Command section.
				elif task.lower() == '/list':
					# Get the models info
					configs_files = self.utility_manager.list_available_models()
					
					# Printing the models info.
					print('Available models:\n')
					for index, model in enumerate(configs_files, 1):
						print(f'{index}. {model}')
					print('', end='\n')

					# Print all the available modes.
					print('Available modes:\n')
					for index, mode in enumerate(['code','script','command','vision','chat'], 1):
						print(f'{index}. {mode}',end='\n')
					
					# Print all the available languages.
					print('\nAvailable languages:\n')
					for index, language in enumerate(['python','javascript'], 1):
						print(f'{index}. {language}')
					
					continue
				
				# UPGRAGE - Command section.
				elif task.lower() == '/upgrade':
					self.utility_manager.upgrade_interpreter()
					continue
				
				# EXECUTE - Command section.
				elif task.lower() == '/execute':
					os_name = os_platform[0].lower()
					self.execute_last_code(os_name)
					continue
				
				# SAVE - Command section.
				elif task.lower() == '/save':
					mode_type = self.INTERPRETER_MODE
					latest_code_extension: str = ""
					
					# Get the OS platform.
					os_name = os_platform[0].lower()

					# Set the script or command extension based on the OS platform and mode type
					extensions = {
						"script": {
							"darwin": ".applescript",
							"linux": ".sh",
							"windows": ".bat"
						},
						"command": {
							"darwin": ".sh",
							"linux": ".sh",
							"windows": ".bat"
						},
						"code": lambda lang: '.py' if lang == 'python' else '.js'
					}

					lower_os_name = os_name.lower()
					if mode_type.lower() in extensions:
						if mode_type.lower() == "code":
							latest_code_extension = extensions["code"](self.INTERPRETER_LANGUAGE)
						else:
							for key in extensions[mode_type.lower()]:
								if key in lower_os_name:
									latest_code_extension = extensions[mode_type.lower()][key]
									break
							else:
								raise ValueError(f"Unsupported operating system: {os_name}")
					else:
						raise ValueError(f"Unsupported mode type: {mode_type}")

					latest_code_name = f"output/{mode_type}_{time.strftime('%Y_%m_%d-%H_%M_%S', time.localtime())}" + latest_code_extension
					latest_code = code_snippet
					self.code_interpreter.save_code(latest_code_name, latest_code)
					display_markdown_message(f"{mode_type.capitalize()} saved successfully to **{latest_code_name}**")
					continue

				# EDIT - Command section.
				elif task.lower() == '/edit':
					# Get the OS platform.
					os_name = os_platform[0].lower()

					code_file, code_snippet = self.utility_manager.get_output_history(mode=self.INTERPRETER_MODE, os_name=os_name, language=self.INTERPRETER_LANGUAGE)
					
					# check if the code is empty
					if code_snippet is None or code_file is None:
						self.logger.error("Code history or file is empty.")
						display_markdown_message("Code history or file is empty. - Please use **-s** flag or **/save** command to save the code.")
						continue

					# Attempt to open with default editor.
					self.logger.info(f"Opening code in default editor for os '{os_platform}'")
					try:
						if 'darwin' in os_name:
							subprocess.call(['open', code_file.name if not isinstance(code_file, str) else code_file])
						elif 'linux' in os_name:
							subprocess.call(['xdg-open', code_file.name if not isinstance(code_file, str) else code_file])
						elif 'windows' in os_name:
							os.startfile(code_file.name if not isinstance(code_file, str) else code_file)
						continue
					except Exception:
						self.logger.warning("Default editor not found. Trying vim...")
						# Check if vim is available
						if shutil.which('vim'):
							self.logger.info(f"Opening code in vim editor {code_file.name if not isinstance(code_file, str) else code_file}")
							subprocess.call(['vim', code_file.name if not isinstance(code_file, str) else code_file])
							continue
						else:
							self.logger.error("No suitable editor found.")
							continue

				# FIX - Command section.
				elif task.lower() == '/fix':

					if not code_error:
						code_error = code_output

					if not code_error:
						display_markdown_message("Error: No error found in the code to fix.")
						continue

					fix_prompt = f"Fix the errors in {self.INTERPRETER_LANGUAGE} language.\nCode is \n'{code_snippet}'\nAnd Error is \n'{code_error}'\n"
					"give me output only in code and no other text or explanation. And comment in code where you fixed the error.\n"
					
					# Start the LLM Request.
					self.logger.info(f"Fix Prompt: {fix_prompt}")
					generated_output = self._generate_content_with_retries(fix_prompt, self.history, config_values=self.config_values, image_file=extracted_file_name)

					# Extract the code from the generated output.
					self.logger.info(f"Generated output type {type(generated_output)}")
					code_snippet = self.code_interpreter.extract_code(generated_output, start_sep, end_sep)
					
					# Display the extracted code.
					if code_snippet:
						self.logger.info(f"Extracted code: {code_snippet[:50]}")
					
						if self.DISPLAY_CODE:
							display_code(code_snippet)
							self.logger.info("Code extracted successfully.")
						
							# Execute the code if the user has selected.
							code_output, code_error = self.execute_code(code_snippet, os_name)
							
							if code_output:
								self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed successfully.")
								display_code(code_output)
								self.logger.info(f"Output: {code_output[:100]}")
							elif code_error:
								self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed with error.")
								display_markdown_message(f"Error: {code_error}")
					continue

				# MODE - Command section.
				elif task.lower() == '/settings' and self.terminal_ui:
					self._apply_runtime_settings(self._open_tui_settings("settings"))
					display_markdown_message("Settings updated.")
					continue

				elif task.lower() == '/mode' and self.terminal_ui:
					self._apply_runtime_settings(self._open_tui_settings("mode"))
					display_markdown_message(f"Mode changed to '{self.INTERPRETER_MODE}'")
					continue

				elif any(command in task.lower() for command in ['/mode ']):
					mode = task.split(' ')[1]
					if mode:
						if mode.lower() not in ['code','script','command','vision','chat']:
							mode = 'code'
							display_markdown_message(f"The input mode is not supported. Mode changed to {mode},"
													 "\nUse '/list' command to get the list of supported modes.")
						else:
							self._apply_mode(mode)
							display_markdown_message(f"Mode changed to '{self.INTERPRETER_MODE}'")
					continue

				# MODEL - Command section.
				elif task.lower() == '/model' and self.terminal_ui:
					self._apply_runtime_settings(self._open_tui_settings("model"))
					display_markdown_message(f"Model changed to '{self.INTERPRETER_MODEL_LABEL}'")
					continue

				elif any(command in task.lower() for command in ['/model ']):
					model = task.split(' ')[1]
					if model:
						model_config_file = f"configs/{model}.config"
						if not os.path.isfile(model_config_file):
							display_markdown_message(f"Model {model} does not exists. Please check the model name using '/list' command.")
							continue
						else:
							self.INTERPRETER_MODEL = model
							self.INTERPRETER_MODEL_LABEL = model
							display_markdown_message(f"Model changed to '{self.INTERPRETER_MODEL}'")
							self.initialize_client()  # Reinitialize the client with new model.
					continue
				
				# LANGUAGE - Command section.
				elif task.lower() in ['/language', '/lang'] and self.terminal_ui:
					self._apply_runtime_settings(self._open_tui_settings("language"))
					display_markdown_message(f"Language changed to '{self.INTERPRETER_LANGUAGE}'")
					continue

				elif any(command in task.lower() for command in ['/language','/lang']):
					split_task = task.split(' ')
					if len(split_task) > 1:
						language = split_task[1]
						if language:
							self.INTERPRETER_LANGUAGE = language
							if language not in ['python', 'javascript']:
								self.INTERPRETER_LANGUAGE = 'python'
								display_markdown_message(f"The input language is not supported. Language changed to {self.INTERPRETER_LANGUAGE}")
							display_markdown_message(f"Language changed to '{self.INTERPRETER_LANGUAGE}'")
					continue
				
				# INSTALL - Command section.
				elif task.lower().startswith('/install'):
					parts = task.split(' ')
					if len(parts) >= 3:
						# Case: /install <language> <package>
						language = parts[1].lower()
						package_name = parts[2]
						
						# Validate language
						if language in ['python', 'py']:
							language = 'python'
						elif language in ['javascript', 'js', 'node']:
							language = 'javascript'
						else:
							# If unknown language, treat as package name to be safe
							package_name = parts[1]
							language = self.INTERPRETER_LANGUAGE
					elif len(parts) == 2:
						package_name = parts[1]
						language = self.INTERPRETER_LANGUAGE
					else:
						display_markdown_message("Usage: **/install [language] <package_name>**")
						continue
					
					# check if package name is not system module.
					system_modules = self.package_manager.get_system_modules()
					
					if package_name in system_modules:
						self.logger.info(f"Package {package_name} is a system module.")
						display_markdown_message(f"Package {package_name} is a system module.")
						continue
						
					if package_name:
						self.logger.info(f"Installing package {package_name} for {language}")
						display_markdown_message(f"Installing package **{package_name}** for **{language}**...")
						try:
							self.package_manager.install_package(package_name, language)
							display_markdown_message(f"Successfully installed **{package_name}**")
						except Exception as ex:
							self.logger.error(f"Manual installation failed: {ex}")
							display_markdown_message(f"Failed to install **{package_name}**: {ex}")
					continue
				
				# Get the prompt based on the mode.
				else:
					prompt = self.get_mode_prompt(task, os_name)
					self.logger.info(f"Prompt init is '{prompt}'")
					
					# Check if the prompt is empty.
					if not prompt:
						display_markdown_message("Please **enter** a valid task.")
						continue

				# Clean the responses
				self.utility_manager._clean_responses()
				
				# Print Model and Mode information.
				self.logger.info(f"Interpreter Mode: {self.INTERPRETER_MODE} Model: {self.INTERPRETER_MODEL}")

				# Check if prompt contains any file uploaded by user.
				extracted_file_name = self.utility_manager.extract_file_name(prompt)
				self.logger.info(f"Input prompt file name: '{extracted_file_name}'")

				if extracted_file_name is not None:
					full_path = self.utility_manager.get_full_file_path(extracted_file_name)
					self.logger.info(f"Input prompt full_path: '{full_path}'")
					
					# Check if image contains URL.
					if 'http' in extracted_file_name or 'https' in extracted_file_name or 'www.' in extracted_file_name:
						self.logger.info("Image contains URL Skipping the file processing.")
					
					else:
						# Check if the file exists and is a file
						if os.path.isfile(full_path):
							# Check if file size is less than 50 KB
							file_size_max = 50000
							file_size = os.path.getsize(full_path)
							self.logger.info(f"Input prompt file_size: '{file_size}'")
							if file_size < file_size_max:
								try:
									with open(full_path, 'r', encoding='utf-8') as file:
										# Check if file extension is .json, .csv, or .xml
										file_extension = os.path.splitext(full_path)[1].lower()
										
										if file_extension in ['.json','.xml']:
											# Split by new line and read only 20 lines
											file_data = '\n'.join(file.readline() for _ in range(20))
											self.logger.info(f"Input prompt JSON/XML file_data: '{str(file_data)}'")
											
										elif file_extension == '.csv':
											# Read only headers of the csv file
											file_data = self.utility_manager.read_csv_headers(full_path)
											self.logger.info(f"Input prompt CSV file_data: '{str(file_data)}'")
											
										else:
											file_data = file.read()
											self.logger.info(f"Input prompt file_data: '{str(file_data)}'")
											
										task_lower = task.lower()
										if any(word in task_lower for word in ['graph', 'graphs', 'chart', 'charts']):
											prompt += "\n" + "This is file data from user input: " + str(file_data) + " use this to analyze the data."
											self.logger.info(f"Input Prompt: '{prompt}'")
										else:
											self.logger.info("The prompt does not contain both 'graph' and 'chart'.")
								except Exception as exception:
									self.logger.error(f"Error reading file: {exception}")
							else:
								self.logger.warning("File size is greater.")
						else:
							self.logger.error("File does not exist or is not a file.")                         
				else:
					self.logger.info("No file name found in the prompt.")
			
				# If graph were requested.
				task_lower = task.lower()
				if any(word in task_lower for word in ['graph', 'graphs']):
					if self.INTERPRETER_LANGUAGE == 'python':
						prompt += "\n" + "using Python use Matplotlib save the graph in file called 'graph.png'"
					elif self.INTERPRETER_LANGUAGE == 'javascript':
						prompt += "\n" + "using JavaScript use Chart.js save the graph in file called 'graph.png'"

				# if Chart were requested
				if any(word in task_lower for word in ['chart', 'charts', 'plot', 'plots']):    
					if self.INTERPRETER_LANGUAGE == 'python':
						prompt += "\n" + "using Python use Plotly save the chart in file called 'chart.png'"
					elif self.INTERPRETER_LANGUAGE == 'javascript':
						prompt += "\n" + "using JavaScript use Chart.js save the chart in file called 'chart.png'"

				# if Table were requested
				if 'table' in task_lower:
					if self.INTERPRETER_LANGUAGE == 'python':
						prompt += "\n" + "using Python use Pandas save the table in file called 'table.md'"
					elif self.INTERPRETER_LANGUAGE == 'javascript':
						prompt += "\n" + "using JavaScript use DataTables save the table in file called 'table.html'"
			
				# Start the LLM Request.     
				self.logger.info(f"Prompt: {prompt}")
				
				# Add the history as memory.
				if self.INTERPRETER_HISTORY and self.INTERPRETER_MODE == 'chat':
					self.history = self.history_manager.get_chat_history(self.history_count)
				
				elif self.INTERPRETER_HISTORY and self.INTERPRETER_MODE == 'code':
					self.history = self.history_manager.get_code_history(self.history_count)
				
				generated_output = self._generate_content_with_retries(prompt, self.history, config_values=self.config_values,image_file=extracted_file_name)
				
				# No extra processing for Vision mode.
				if self.INTERPRETER_MODE in ['vision', 'chat']:
					display_markdown_message(f"{generated_output}")
					continue

				# Extract the code from the generated output.
				self.logger.info(f"Generated output type {type(generated_output)}")
				code_snippet = self.code_interpreter.extract_code(generated_output, start_sep, end_sep)
				code_snippet = self._maybe_simplify_generated_code(task, code_snippet)
				display_language = self.INTERPRETER_LANGUAGE if self.CODE_MODE else 'bash'
				
				# Display the extracted code.
				if code_snippet:
					self.logger.info(f"Extracted code: {code_snippet[:50]}")
				
				should_display_code = bool(code_snippet) and (
					self.DISPLAY_CODE or (self.INTERPRETER_PROMPT_INPUT and not self.SAVE_CODE and not self.EXECUTE_CODE)
				)
				if should_display_code:
					display_code(code_snippet, language=display_language)
					self.logger.info("Code extracted successfully.")
				elif not code_snippet:
					if generated_output:
						if self.INTERPRETER_MODE in ['code', 'script', 'command']:
							display_code(generated_output, language=display_language)
						else:
							display_markdown_message(f"{generated_output}")
						display_markdown_message("No executable code block was returned, so the raw model response is shown above.")
					else:
						display_markdown_message("The model returned an empty response.")
				
				if code_snippet:
					current_time = time.strftime("%Y_%m_%d-%H_%M_%S", time.localtime())
					
					if self.INTERPRETER_LANGUAGE == 'javascript' and self.SAVE_CODE and self.CODE_MODE:
						self.code_interpreter.save_code(f"output/code_{current_time}.js", code_snippet)
						self.logger.info("JavaScript code saved successfully.")
					
					elif self.INTERPRETER_LANGUAGE == 'python' and self.SAVE_CODE and self.CODE_MODE:
						self.code_interpreter.save_code(f"output/code_{current_time}.py", code_snippet)
						self.logger.info(f"{self.INTERPRETER_LANGUAGE} code saved successfully.")
					
					elif self.SAVE_CODE and self.COMMAND_MODE:
						self.code_interpreter.save_code(f"output/command_{current_time}.txt", code_snippet)
						self.logger.info("Command saved successfully.")

					elif self.SAVE_CODE and self.SCRIPT_MODE:
						self.code_interpreter.save_code(f"output/script_{current_time}.txt", code_snippet)
						self.logger.info("Script saved successfully.")
				
					# Execute the code if the user has selected.
					code_output, code_error = self._execute_generated_output(code_snippet, os_name)
					
					if code_output:
						self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed successfully.")
						display_code(code_output)
						self.logger.info(f"Output: {code_output[:100]}")
					elif code_error and code_error.startswith("Safety blocked:"):
						self.logger.warning(code_error)
					elif code_error:
						self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed with error.")
						display_markdown_message(f"Error: {code_error}")
					else:
						display_markdown_message("Execution completed successfully. No stdout was produced.")
						
					# install Package on error.
					error_messages = ["ModuleNotFound", "ImportError", "No module named", "Cannot find module"]
					if code_error is not None and any(error_message in code_error for error_message in error_messages):
						package_name = self.package_manager.extract_package_name(code_error, self.INTERPRETER_LANGUAGE)
						
						# check if package name is not system module.
						system_modules = self.package_manager.get_system_modules()
						
						# Skip installing system modules.
						if package_name in system_modules:
							self.logger.info(f"Package {package_name} is a system module.")
							display_markdown_message(f"Package {package_name} is a system module.")
							raise Exception(f"Package {package_name} is a system module.")
						
						if package_name:
							for attempt in range(1, 4):
								try:
									self.logger.info(f"Installing package {package_name} on interpreter {self.INTERPRETER_LANGUAGE} (Attempt {attempt}/3)")
									self.package_manager.install_package(package_name, self.INTERPRETER_LANGUAGE)

									# Wait and Execute the code again.
									time.sleep(3)
									code_output, code_error = self._execute_generated_output(code_snippet, os_name, force_execute=True)
									if code_output:
										self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed successfully.")
										display_code(code_output)
										self.logger.info(f"Output: {code_output[:100]}")
									elif code_error:
										self.logger.info(f"{self.INTERPRETER_LANGUAGE} code executed with error.")
										display_markdown_message(f"Error: {code_error}")
									else:
										display_markdown_message("Execution completed successfully. No stdout was produced.")
									break  # Exit retry loop on success
								except Exception as ex:
									if attempt < 3:
										self.logger.warning(f"Attempt {attempt} to install package {package_name} failed: {ex}")
										display_markdown_message(f"Attempt {attempt}/3 to install package **{package_name}** failed. Retrying in 2 seconds...")
										time.sleep(2)
									else:
										self.logger.error(f"Failed to install package {package_name} after 3 attempts: {ex}")
										display_markdown_message(f"Failed to install package **{package_name}** after 3 attempts. Error: {ex}. Proceeding with repair logic...")

					if code_error and not code_error.startswith("Safety blocked:"):
						code_snippet, repaired_output, repaired_error = self._attempt_repair_after_failure(
							task,
							prompt,
							code_snippet,
							code_error,
							os_name,
							start_sep,
							end_sep,
							extracted_file_name,
							code_output=code_output,
						)
						if repaired_output:
							code_output = repaired_output
							code_error = repaired_error
							display_code(repaired_output)
						elif repaired_error and repaired_error != code_error:
							code_error = repaired_error
							display_markdown_message(f"Error: {repaired_error}")
							
					try:
						# Check if graph.png exists and open it.
						self.utility_manager._open_resource_file('graph.png')
						
						# Check if chart.png exists and open it.
						self.utility_manager._open_resource_file('chart.png')
						
						# Check if table.md exists and open it.
						self.utility_manager._open_resource_file('table.md')
					except Exception as exception:
						display_markdown_message(f"Error in opening resource files: {str(exception)}")
				
				self.history_manager.save_history_json(task, self.INTERPRETER_MODE, os_name, self.INTERPRETER_LANGUAGE, prompt, code_snippet,code_output, self.INTERPRETER_MODEL)
				
			except Exception as exception:
				error_text = str(exception)
				if self._is_recoverable_runtime_error(error_text):
					self.logger.warning(f"Recoverable interpreter error: {error_text}")
					display_markdown_message(f"Request failed: {self._format_runtime_error_message(error_text)}")
					display_markdown_message("Try `/model <name>` to switch models or `/list` to see the available options.")
					continue
				self.logger.error(f"An error occurred in interpreter_lib: {error_text}")
				raise