# -*- coding: utf-8 -*-
"""Export REPL/session history to Jupyter notebooks (Issue #223)."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


def export_to_notebook(
	cells: List[Dict[str, Any]],
	output_path: Optional[str] = None,
	title: str = "Code Interpreter Session",
	*,
	home: Optional[Path] = None,
) -> str:
	"""Convert a session's code+output history to a .ipynb file."""
	nb = {
		"nbformat": 4,
		"nbformat_minor": 5,
		"metadata": {
			"kernelspec": {
				"display_name": "Python 3",
				"language": "python",
				"name": "python3",
			},
			"language_info": {"name": "python", "version": "3.10.0"},
		},
		"cells": [],
	}

	nb["cells"].append(
		{
			"cell_type": "markdown",
			"metadata": {},
			"source": [
				f"# {title}\n",
				f"*Generated by Code Interpreter on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n",
			],
		}
	)

	for cell in cells or []:
		ctype = (cell.get("type") or "code").lower()
		source = cell.get("source") or ""
		if ctype == "markdown":
			nb["cells"].append(
				{
					"cell_type": "markdown",
					"metadata": {},
					"source": _as_lines(source),
				}
			)
		else:
			outputs = []
			if cell.get("output"):
				outputs.append(
					{
						"output_type": "stream",
						"name": "stdout",
						"text": _as_lines(str(cell["output"])),
					}
				)
			nb["cells"].append(
				{
					"cell_type": "code",
					"execution_count": None,
					"metadata": {},
					"source": _as_lines(source),
					"outputs": outputs,
				}
			)

	if output_path:
		path = Path(output_path).expanduser()
	else:
		base = Path(home) if home is not None else Path.home()
		outdir = base / ".code_interpreter" / "notebooks"
		outdir.mkdir(parents=True, exist_ok=True)
		path = outdir / f"session_{datetime.now().strftime('%Y%m%d_%H%M%S')}.ipynb"

	path.parent.mkdir(parents=True, exist_ok=True)
	path.write_text(json.dumps(nb, indent=2), encoding="utf-8")
	logger.info("Notebook exported to %s", path)
	return str(path)


def _as_lines(text: str) -> List[str]:
	if text.endswith("\n"):
		return text.splitlines(keepends=True)
	lines = text.splitlines(keepends=True)
	if lines and not lines[-1].endswith("\n"):
		lines[-1] = lines[-1] + "\n"
	if not lines:
		return [""]
	return lines
